export const ezConfigMock = {
    adminUiConfig: {
        multiFileUpload: {
            locationMappings: [],
            defaultMappings: [
                {
                    mimeTypes: [
                        'image/jpeg',
                        'image/jpg',
                        'image/pjpeg',
                        'image/pjpg',
                        'image/png',
                        'image/bmp',
                        'image/gif',
                        'image/tiff',
                        'image/x-icon',
                        'image/webp',
                    ],
                    contentTypeIdentifier: 'image',
                    contentFieldIdentifier: 'image',
                    nameFieldIdentifier: 'name',
                },
                {
                    mimeTypes: [
                        'image/svg+xml',
                        'application/msword',
                        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                        'application/vnd.ms-excel',
                        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                        'application/vnd.ms-powerpoint',
                        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                        'application/pdf',
                    ],
                    contentTypeIdentifier: 'file',
                    contentFieldIdentifier: 'file',
                    nameFieldIdentifier: 'name',
                },
            ],
            fallbackContentType: {
                contentTypeIdentifier: 'file',
                contentFieldIdentifier: 'file',
                nameFieldIdentifier: 'name',
            },
            maxFileSize: 5242880,
        },
        sortFieldMappings: {
            PATH: 'LocationPath',
            PUBLISHED: 'DatePublished',
            MODIFIED: 'DateModified',
            SECTION: 'SectionIdentifier',
            DEPTH: 'LocationDepth',
            PRIORITY: 'LocationPriority',
            NAME: 'ContentName',
            NODE_ID: 'LocationId',
            CONTENTOBJECT_ID: 'ContentId',
        },
        sortOrderMappings: { ASC: 'ascending', DESC: 'descending' },
        languages: {
            mappings: {
                'eng-GB': { name: 'English (United Kingdom)', id: 2, languageCode: 'eng-GB', enabled: true },
                'fre-FR': { name: 'French', id: 4, languageCode: 'fre-FR', enabled: true },
                'ger-DE': { name: 'German', id: 8, languageCode: 'ger-DE', enabled: true },
                'nor-NO': { name: 'Norwegian', id: 16, languageCode: 'nor-NO', enabled: true },
            },
            priority: ['eng-GB', 'fre-FR', 'ger-DE', 'nor-NO'],
        },
        contentTypes: {
            Content: [
                {
                    identifier: 'about',
                    name: 'About',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#about',
                    href: '/api/ezp/v2/content/types/21',
                },
                {
                    identifier: 'article',
                    name: 'Article',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#article',
                    href: '/api/ezp/v2/content/types/16',
                },
                {
                    identifier: 'blog',
                    name: 'Blog',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#blog',
                    href: '/api/ezp/v2/content/types/17',
                },
                {
                    identifier: 'blog_post',
                    name: 'Blog post',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#blog_post',
                    href: '/api/ezp/v2/content/types/18',
                },
                {
                    identifier: 'folder',
                    name: 'Folder',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#folder',
                    href: '/api/ezp/v2/content/types/1',
                },
                {
                    identifier: 'form',
                    name: 'Form',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#form',
                    href: '/api/ezp/v2/content/types/26',
                },
                {
                    identifier: 'place',
                    name: 'Place',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#place',
                    href: '/api/ezp/v2/content/types/19',
                },
                {
                    identifier: 'product',
                    name: 'Product',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#product',
                    href: '/api/ezp/v2/content/types/14',
                },
                {
                    identifier: 'product_list',
                    name: 'Product List',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#file',
                    href: '/api/ezp/v2/content/types/13',
                },
                {
                    identifier: 'subscribe',
                    name: 'Subscribe',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#file',
                    href: '/api/ezp/v2/content/types/22',
                },
                {
                    identifier: 'place_list',
                    name: 'Place list',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#file',
                    href: '/api/ezp/v2/content/types/20',
                },
            ],
            Users: [
                {
                    identifier: 'user',
                    name: 'User',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#user',
                    href: '/api/ezp/v2/content/types/4',
                },
                {
                    identifier: 'user_group',
                    name: 'User group',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#user_group',
                    href: '/api/ezp/v2/content/types/3',
                },
            ],
            Media: [
                {
                    identifier: 'file',
                    name: 'File',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#file',
                    href: '/api/ezp/v2/content/types/23',
                },
                {
                    identifier: 'gallery',
                    name: 'Gallery',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#gallery',
                    href: '/api/ezp/v2/content/types/15',
                },
                {
                    identifier: 'image',
                    name: 'Image',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#image',
                    href: '/api/ezp/v2/content/types/5',
                },
                {
                    identifier: 'video',
                    name: 'Video',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#video',
                    href: '/api/ezp/v2/content/types/24',
                },
            ],
            Pages: [
                {
                    identifier: 'landing_page',
                    name: 'Landing page',
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#landing_page',
                    href: '/api/ezp/v2/content/types/25',
                },
            ],
        },
        contentTypeNames: {
            about: 'About',
            article: 'Article',
            blog: 'Blog',
            blog_post: 'Blog post',
            folder: 'Folder',
            form: 'Form',
            place: 'Place',
            product: 'Product',
            product_list: 'Product List',
            subscribe: 'Subscribe',
            place_list: 'Place list',
            user: 'User',
            user_group: 'User group',
            file: 'File',
            gallery: 'Gallery',
            image: 'Image',
            video: 'Video',
            landing_page: 'Landing page',
        },
        universalDiscoveryWidget: { startingLocationId: 1 },
        subItems: { limit: 10 },
        imageAssetMapping: {
            contentTypeIdentifier: 'image',
            contentFieldIdentifier: 'image',
            nameFieldIdentifier: 'name',
            parentLocationId: 51,
        },
        notifications: { error: { timeout: 0 }, warning: { timeout: 0 }, info: { timeout: 0 }, success: { timeout: 5000 } },
        timezone: 'Europe/Warsaw',
        dateFormat: {
            fullDateTime: 'LLLL dd, yyyy HH:mm',
            fullDate: 'LLLL dd, yyyy',
            fullTime: 'HH:mm',
            shortDateTime: 'dd/MM/yyyy HH:mm',
            shortDate: 'dd/MM/yyyy',
            shortTime: 'HH:mm',
            full: 'LLLL dd, yyyy HH:mm',
            short: 'dd/MM/yyyy HH:mm',
        },
        contentTree: {
            loadMoreLimit: 30,
            childrenLoadMaxLimit: 200,
            treeMaxDepth: 10,
            allowedContentTypes: [],
            ignoredContentTypes: [],
            treeRootLocationId: 2,
            contextualTreeRootLocationIds: [2, 5, 43, 48, 249],
        },
    },
    errors: {
        emailRegexp: {},
        emptyField: '{fieldName} field is required',
        invalidEmail: 'A valid email address is required',
        invalidUrl: 'A valid URL is required',
        tooLong: '{fieldName} value should be less than or equal to {maxLength} characters',
        tooShort: '{fieldName} value should be greater than or equal to {minLength} characters',
        isNotInteger: '{fieldName} value should be an integer',
        isNotFloat: '{fieldName} value should be a float number',
        isLess: '{fieldName} value should be greater than or equal to {minValue}',
        isGreater: '{fieldName} value should be less than or equal to {maxValue}',
        invalidFileSize: '{fieldName}: Cannot upload. File exceeds file size limit.',
        provideLatitudeValue: 'Provide latitude value in the Latitude field',
        provideLongitudeValue: 'Provide longitude value in the Longitude field',
        addressNotFound: 'Provided address does not exist',
        notSamePasswords: 'Passwords do not match',
        invalidValue: '{fieldName} field has invalid values',
        outOfRangeValue: '{fieldName} field value is out of range. The value has to be between {min} and {max}',
    },
    modules: {},
    udwTabs: {},
    helpers: { text: {}, request: {}, notification: {}, timezone: {}, contentType: {} },
    core: {},
    formBuilder: {
        config: {
            fieldsConfig: [
                {
                    identifier: 'single_line',
                    name: 'Single line input',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'placeholder',
                            name: 'Placeholder',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'default_value',
                            name: 'Default value',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [
                        { identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'min_length', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'max_length', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'regex', category: 'default', constraints: [], options: [], defaultValue: null },
                    ],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#input-line',
                },
                {
                    identifier: 'multi_line',
                    name: 'Multiple line input',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'placeholder',
                            name: 'Placeholder',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'default_value',
                            name: 'Default value',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [{ identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null }],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#input-line-multiple',
                },
                {
                    identifier: 'number',
                    name: 'Number',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'placeholder',
                            name: 'Placeholder',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'default_value',
                            name: 'Default value',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [
                        { identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'min_value', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'max_value', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'regex', category: 'default', constraints: [], options: [], defaultValue: null },
                    ],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#input-number',
                },
                {
                    identifier: 'checkbox',
                    name: 'Checkbox',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [{ identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null }],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#checkbox',
                },
                {
                    identifier: 'checkbox_list',
                    name: 'Checkboxes',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'help',
                            name: 'Help',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'options',
                            name: 'Options',
                            type: 'choices',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [
                        { identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'min_choices', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'max_choices', category: 'default', constraints: [], options: [], defaultValue: null },
                    ],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#checkbox-multiple',
                },
                {
                    identifier: 'radio',
                    name: 'Radio',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'options',
                            name: 'Options',
                            type: 'choices',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [{ identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null }],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#radio-button-multiple',
                },
                {
                    identifier: 'dropdown',
                    name: 'Dropdown',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'options',
                            name: 'Options',
                            type: 'choices',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [{ identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null }],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#dropdown',
                },
                {
                    identifier: 'email',
                    name: 'Email',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'placeholder',
                            name: 'Placeholder',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [
                        { identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'regex', category: 'default', constraints: [], options: [], defaultValue: null },
                    ],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#mail',
                },
                {
                    identifier: 'date',
                    name: 'Date',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'placeholder',
                            name: 'Placeholder',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'format',
                            name: 'Date format',
                            type: 'select',
                            category: 'default',
                            constraints: { not_blank: { message: 'You must provide date format' } },
                            options: {
                                choices: {
                                    'mm/dd/yyyy': 'MM/dd/yyyy',
                                    'dd/mm/yyyy': 'dd/MM/yyyy',
                                    'dd/mm': 'dd/MM',
                                    'mm/dd': 'MM/dd',
                                    'mm/yyyy': 'MM/yyyy',
                                    yyyy: 'yyyy',
                                },
                            },
                            defaultValue: 'MM/dd/yyyy',
                        },
                        {
                            identifier: 'current_date_as_default_value',
                            name: 'Current date as default value',
                            type: 'checkbox',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [{ identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null }],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#date',
                },
                {
                    identifier: 'url',
                    name: 'URL',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'placeholder',
                            name: 'Placeholder',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'default_value',
                            name: 'Default value',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [{ identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null }],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#link',
                },
                {
                    identifier: 'file',
                    name: 'File',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'location',
                            name: 'Select file upload location',
                            type: 'location',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [
                        { identifier: 'required', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'upload_size', category: 'default', constraints: [], options: [], defaultValue: null },
                        { identifier: 'extensions', category: 'default', constraints: [], options: [], defaultValue: null },
                    ],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#upload',
                },
                {
                    identifier: 'captcha',
                    name: 'Captcha',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'help',
                            name: 'Help text',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#captcha',
                },
                {
                    identifier: 'button',
                    name: 'Button',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'action',
                            name: 'Action',
                            type: 'action',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                        {
                            identifier: 'notification_email',
                            name: 'Notification email(s)',
                            type: 'string',
                            category: 'default',
                            constraints: [],
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#button',
                },
                {
                    identifier: 'hidden',
                    name: 'Hidden field',
                    category: 'Basic form fields',
                    attributes: [
                        {
                            identifier: 'value',
                            name: 'Default value',
                            type: 'string',
                            category: 'default',
                            constraints: { not_blank: { message: 'You must provide value of the field' } },
                            options: [],
                            defaultValue: null,
                        },
                    ],
                    validators: [],
                    thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#input-hidden',
                },
            ],
        },
    },
};
